spring.application.name=auth-service
management.endpoints.enabled-by-default=true
logging.level.root=INFO
logging.level.com.localhost.auth=DEBUG
management.endpoints.web.exposure.include=*
spring.grpc.client.channels.customer.address=0.0.0.0:50005
#spring.grpc.client.enabled=true
spring.grpc.server.enabled=false
